### ISSUE TITLE
Make tagged releases

### ISSUE THREAD

**Issue by PureTryOut** [forslund/skill-cocktail#13]
Hey forslund, nice to see you make personal skills as well!

As you know I'm packaging the skills for Alpine Linux, but to do so I need tagged git releases. Could you start doing that for your cocktail skill?

**Comment by forslund** [comment]
I'm away from my computer right now but tomorrow morning I'll do it

**Comment by forslund** [comment]
Tagged [v1.0](https://github.com/forslund/skill-cocktail/releases/tag/v1.0)

**Comment by PureTryOut** [comment]
Thanks! Could you add a license to the project while you're at it?
