### ISSUE TITLE
TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by PureTryOut** [forslund/skill-cocktail#14]
This happens when querying for "how do I make a sex on the beach". The example from the README "how do I mix a moscow mule" works fine however.

**Comment by forslund** [comment]
This seems to be a duplicate of of #12, gonna see if I can replicate this lookup and error.

**Comment by PureTryOut** [comment]
Oh woops sorry, I didn't see anything related to a API lookup so I just assumed the error was different.

**Comment by forslund** [comment]
I merged a probable fix for this issue. Let me know if latest master works for you.

**Comment by PureTryOut** [comment]
It took ages for it to find something, but it managed to. Yup it works now, thanks!
